package com.digitalsoftware.livdev.rempahasli;

import java.util.ArrayList;

public class RempahData {
    public static String[][] data = new String[][]{
            {"Cengkih", "Cengkih, cengkeh atau cingkeh (Syzygium aromaticum) merupakan tanaman rempah yang termasuk dalam komoditas sektor perkebunan. Menurut Balai Besar Penelitian dan Pengembangan Pasca Panen Pertanian, sejak tahun 22 sebelum Masehi, cengkih digunakan sebagai pewangi alami.Seiiring berkembangnya zaman dan teknologi, maka cengkih tidak hanya sekadar digunakan sebagai bahan dari campuran tembakau/rokok. Potensi tanaman cengkih antara lain sebagai bahan alami untuk obat anti nyamuk. Kemudian senyawa yang terdapat dalam daun cengkih yaitu eugenol memiliki khasiat sebagai antibakteri.", "https://upload.wikimedia.org/wikipedia/commons/f/f0/Cloves-spice.jpg"},
            {"Pala", "Pala (Myristica fragrans) merupakan tumbuhan berupa pohon yang berasal dari kepulauan Banda, Maluku. Akibat nilainya yang tinggi sebagai rempah-rempah, buah dan biji pala telah menjadi komoditi perdagangan yang penting sejak masa Romawi. Pala disebut-sebut dalam ensiklopedia karya Plinius \"Si Tua\". Biji bijinya mengandung banyak zat yang bermanfaat bagi tubuh manusia. Misalnya Atsiri, Saponin, Enzim Lipase, hingga Pektin. Buah pala juga dapat mengobati penyakit susah tidur, masuk angin, rematik, serta melancarkan pencernaan dan meringankan nyeri haid.", "https://doktersehat.com/wp-content/uploads/2019/06/biji-pala-doktersehat.jpeg"},
            {"Lada", "Lada, disebut juga Merica/Sahang, yang mempunyai nama Latin Piper Albi Linn adalah sebuah tanaman yang kaya akan kandungan kimia, seperti minyak lada, minyak lemak, juga pati. Lada bersifat sedikit pahit, pedas, hangat, dan antipiretik. Tanaman ini sudah mulai ditemukan dan dikenal sejak puluhan abad yang lalu.", "https://upload.wikimedia.org/wikipedia/commons/3/31/Black_Pepper_%28Piper_nigrum%29_fruits.jpg"},
            {"Andaliman", "Andaliman adalah bumbu masak khas Asia yang berasal dari kulit luar buah beberapa jenis tumbuhan anggota marga Zanthoxylum (suku jeruk-jerukan, Rutaceae). Bumbu ini di Indonesia hanya dikenal untuk masakan Batak, sehingga dikenal orang luar daerah ini sebagai \"merica batak\".", "https://upload.wikimedia.org/wikipedia/commons/0/06/Poivre_fond_blanc.jpg"},
            {"Kapulaga", "Kapulaga adalah sejenis rempah yang dihasilkan dari biji beberapa tanaman dari genera Elettaria dan Amomum dalam keluarga Zingiberaceae (keluarga jahe-jahean). Kedua genera ini adalah tanaman asli Bangladesh, Bhutan, India, Indonesia, Nepal, dan Pakistan; biji kapulaga dapat dikenali dari biji polongnya yang kecil, penampang irisan segitiga, dan berbentuk gelendong kumparan, dengan kulit luar yang tipis, dan biji hitam yang kecil.", "https://www.kampustani.com/wp-content/uploads/2019/02/Cara-Budidaya-Kapulaga-Yang-Benar.jpg"},
            {"Kayu Manis", "Kayu manis (Cinnamomum verum, sin. C. zeylanicum) ialah sejenis pohon penghasil rempah-rempah. Termasuk ke dalam jenis rempah-rempah yang amat beraroma, manis, dan pedas. Orang biasa menggunakan rempah-rempah dalam makanan yang dibakar manis, anggur panas. Kulit manis Ceylon sering kali hanya menggunakan kulit bagian dalam yang lebih tipis, lebih memiliki kesegaran, kurang padat, lebih beraroma, dan lebih lembut dalam rasa daripada kasiavera. Kasiavera memiliki rasa yang lebih kuat (sering lebih pedas) daripada kulit manis Sri Lanka dan umumnya berwarna merah kecoklatan sedang hingga ringan, keras dan bertekstur kayu, serta lebih tebal (2–3 mm (0,079–0,12 inci) dan menggunakan seluruh lapisan kulitnya.", "https://upload.wikimedia.org/wikipedia/commons/d/de/Cinnamomum_verum.jpg"},
            {"Kemukus", "Kemukus (Piper cubeba L.) adalah tanaman yang tergolong dalam genus Piper, yang ditanam untuk diambil buah dan minyak atsirinya. Tanaman ini berasal dan banyak ditanam di Jawa dan Sumatra, sehingga disebut juga sebagai lada jawa atau cabe jawa (\"Java pepper\"), meskipun cabe jawa adalah nama bagi rempah lain (P. retrofractum dan P. longum) yang masih serupa. Buah kemukus kering digunakan sebagai bumbu rempah dalam masakan, terutama masakan Indonesia. Kegunaan lain adalah sebagai penguat rasa pada gin dan rokok. Namun kegunaan penting kemukus adalah sebagai bahan farmakope dan sumber minyak atsiri.", "https://upload.wikimedia.org/wikipedia/commons/0/00/Cubeb.JPG"},
            {"Daun Gedi", "Daun Gedi (Sayor Yondok) (Abelmoschus manihot, sebelumnya dinamakan sebagai Hibiscus Manihot L.). Daun gedi mempunyai fungsi sebagai penambah rasa gurih serta mengentalkan. Selain lezat, daun gedi juga kaya akan vitamin A, zat besi dan serat yang baik untuk saluran pencernaan. Kolagen terkandung di dalam daun ini juga bermanfaat antioksidan dan menjaga kesehatan kulit. Mungkin karena banyak mengandung serat sehingga menyerap kolesterol dan lemak. Sehingga banyak orang berpendapat bahwa sayur ini dapat membuat orang langsing dan membantu menurunkan kadar kolesterol dan hipertensi. Namun belum ada penelitian khusus tentang hal ini.", "http://1.bp.blogspot.com/-7KAan_MyNzM/TZLKClilOYI/AAAAAAAABrY/CpgAoiQlcBg/s1600/daun+gedi+3.jpg"},
            {"Kemiri", "Kemiri (Aleurites moluccana), adalah tumbuhan yang bijinya dimanfaatkan sebagai sumber minyak dan rempah-rempah. Tumbuhan ini masih sekerabat dengan singkong dan termasuk dalam suku Euphorbiaceae. Dalam perdagangan antarnegara dikenal sebagai candleberry, Indian walnut, serta candlenut. Pohonnya disebut sebagai varnish tree atau kukui nut tree. Minyak yang diekstrak dari bijinya berguna dalam industri untuk digunakan sebagai bahan campuran cat. Beberapa bagian dari tanaman ini sudah digunakan dalam obat-obatan tradisional di daerah-daerah pedalaman. Minyaknya digunakan sebagai bahan tambahan dalam perawatan rambut (untuk menyuburkan rambut). Bijinya dapat digunakan sebagai pencahar. Di Jepang, kulit kayunya telah digunakan untuk tumor. Di Sumatera, bijinya dibakar dengan arang, lalu dioleskan di sekitar pusar untuk menyembuhkan diare. Di Jawa, kulit batangnya digunakan untuk mengobati diare atau disentri.", "https://upload.wikimedia.org/wikipedia/commons/c/c7/Aleur_moluc_080716_1050_Fr_ayot.JPG"},
            {"Asam Jawa", "Asam jawa, asam atau asem adalah sejenis buah yang masam rasanya; biasa digunakan sebagai campuran bumbu dalam banyak masakan Indonesia sebagai perasa atau penambah rasa asam dalam makanan, misalnya pada sayur asam atau kadang-kadang pada kuah pempek. Asam juga digunakan untuk campuran jamu tradisional yang dijual oleh penjual jamu keliling.", "https://upload.wikimedia.org/wikipedia/commons/a/a7/Tamarind.jpg"},
    };

    public static ArrayList<Rempah> getListData(){
        ArrayList<Rempah> list = new ArrayList<>();
        for (String[] aData : data) {
            Rempah rempah = new Rempah();
            rempah.setName(aData[0]);
            rempah.setFrom(aData[1]);
            rempah.setPhoto(aData[2]);

            list.add(rempah);
        }
        return list;
    }
}
